#!/usr/bin/env bash
# This script creates a file, displays some messages and deletes a file

major() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && major' SIGTERM
  trap 'major' SIGQUIT
done
